### ISSUE TITLE
examples/atis/preprocess.py pickle issue

### ISSUE THREAD

**Issue by Kandarp2516** [kaniblu/pytorch-bilstmcrf#7]
In Python3, it fails with error:

> Traceback (most recent call last):
>   File "preprocess.py", line 45, in <module>
>     preprocess(args)
>   File "preprocess.py", line 30, in preprocess
>     encoding="binary")
> ImportError: No module named 'numpy.core.multiarray\r'

Seems like pickle error. Might be because it was pickled on other platform and I am trying to use it on windows.

Is there any workaround for this?

**Comment by Kandarp2516** [comment]
Solved this by replacing \r\n to \n 
using method described [here](https://stackoverflow.com/questions/2384302/using-python-to-replace-r-r-n-with-r-n-in-a-binary-file?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)
